plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// lombok
	implementation 'org.projectlombok:lombok:1.18.30'
	annotationProcessor 'org.projectlombok:lombok:1.18.30'
	// json
	implementation 'org.json:json:20240303'
	// apache pdf box
	implementation 'org.apache.pdfbox:pdfbox:3.0.4'
	// thymeleaf
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf:3.3.2'

	// tesseract for java
	implementation 'net.sourceforge.tess4j:tess4j:5.15.0'
}

tasks.named('test') {
	useJUnitPlatform()
}
